//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Data_Table
    {
        public int ID { get; set; }
        public Nullable<int> Employee_s_payroll_information { get; set; }
        public Nullable<int> Social_security_number { get; set; }
        public Nullable<int> Employee_ID { get; set; }
        public Nullable<int> salary { get; set; }
    
        public virtual Employees_Table Employees_Table { get; set; }
    }
}
